php-apache-certbot:
  image: monkeycompany/php-apache-certbot
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'example.com'
    EMAIL: 'admin@example.com'
    PAGESPEED: 'true'
    MODULES: 'cache,cache_disk,cache_socache'
  volumes:
    - ${PWD}/gluster/certs/:/etc/letsencrypt/
    - ${PWD}/gluster/conf/:/opt/docker/etc/httpd/
    - ${PWD}/gluster/www/:/app/
